language: erlang
otp_release:
  - 26.1.1
  - 25.3.2.6
  - 24.3.1
  - 23.3.1
  - 22.3.4.25
before_script:
  - rebar3 get-deps
script:
  - rebar3 compile
  - rebar3 eunit -s uuid
  - make app
after_script:
  - rebar3 clean
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - mjtruog@gmail.com
  irc:
    channels:
      - "irc.oftc.net#cloudi"
    template:
      - "%{repository_slug} (%{branch} - %{commit}) %{author}: %{commit_message}"
      - "View Changes %{compare_url}"
      - "Build #%{build_number}: %{message} (%{build_url})"
    on_success: change
    on_failure: always
